spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot?charset=utf8mb4&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mqtt:
    host: tcp://121.36.54.71:1883
    client-id: testClientId
    default-topic: testTopic
    completion-timeout: 10000
    username: root
    password: cqmike

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true

#logging:
#  level:
#    root: debug
server:
  port: 8081
